package decoders

// Canonical measurement names for pipeline schemas.
// Device JSON tags may stay vendor-native; Measurement.Name should use these.
const (
	BatteryVoltage   = "battery_voltage"
	BatteryPercent   = "battery_percentage"
	Temperature      = "temperature"
	Humidity         = "humidity"
	ExternalTemp     = "external_temperature"
	ExternalHumidity = "external_humidity"
	DSTemperature    = "ds_temperature"
	TMP117Temp       = "tmp117_temperature"
	Illumination     = "illumination"
	ADCVoltage       = "adc_voltage"
	DistanceMM       = "distance_mm"
	DistanceCM       = "distance_cm"
	Distance         = "distance"
	CO2PPM           = "co2_ppm"
	TVOCPPB          = "tvoc_ppb"
	Latitude         = "latitude"
	Longitude        = "longitude"
	Altitude         = "altitude"
	Roll             = "roll"
	Pitch            = "pitch"
	HDOP             = "hdop"
	CurrentMA        = "ma"
	CurrentMALow     = "ma_low"
	CurrentMAHigh    = "ma_high"
	Value            = "value"
	SoilMoisture     = "soil_moisture"
	SoilTemp         = "soil_temperature"
	SoilConductivity = "soil_conductivity"
	SoilPH           = "soil_ph"
	SoilN            = "soil_n"
	SoilP            = "soil_p"
	SoilK            = "soil_k"
	LeafMoisture     = "leaf_moisture"
	LeafTemp         = "leaf_temperature"
	Weight           = "weight"
	InterruptCount   = "interrupt_count"
	ExtiCount        = "exti_count"
	SystemTimestamp  = "system_timestamp"
	DoorOpenStatus   = "door_open_status"
	WaterLeakStatus  = "water_leak_status"
	Alarm            = "alarm"
)

// Canonical units.
const (
	Volt       = "V"
	Celsius    = "C"
	Percent    = "%"
	Millimeter = "mm"
	Centimeter = "cm"
	PPM        = "ppm"
	PPB        = "ppb"
	MilliAmp   = "mA"
	Lux        = "lx"
	Count      = "count"
	Degree     = "deg"
	Meter      = "m"
	Gram       = "g"
	MicroSiemens = "uS/cm"
	Ohm        = "ohm"
)
