package decoders

// Canonical measurement names for pipeline schemas.
// Device JSON tags may stay vendor-native; Measurement.Name should use these.
const (
	BatteryVoltage   = "battery_voltage"
	BatteryPercent   = "battery_percentage"
	Temperature      = "temperature"
	Humidity         = "humidity"
	ExternalTemp     = "external_temperature"
	ExternalHumidity = "external_humidity"
	DSTemperature    = "ds_temperature"
	TMP117Temp       = "tmp117_temperature"
	Illumination     = "illumination"
	ADCVoltage       = "adc_voltage"
	DistanceMM       = "distance_mm"
	DistanceCM       = "distance_cm"
	Distance         = "distance"
	CO2PPM           = "co2_ppm"
	TVOCPPB          = "tvoc_ppb"
	Latitude         = "latitude"
	Longitude        = "longitude"
	Altitude         = "altitude"
	Roll             = "roll"
	Pitch            = "pitch"
	HDOP             = "hdop"
	CurrentMA        = "ma"
	CurrentMALow     = "ma_low"
	CurrentMAHigh    = "ma_high"
	Value            = "value"
	SoilMoisture     = "soil_moisture"
	SoilTemp         = "soil_temperature"
	SoilConductivity = "soil_conductivity"
	SoilPH           = "soil_ph"
	SoilN            = "soil_n"
	SoilP            = "soil_p"
	SoilK            = "soil_k"
	LeafMoisture     = "leaf_moisture"
	LeafTemp         = "leaf_temperature"
	Weight           = "weight"
	VibrationCount   = "vibration_count"
	WorkMinutes      = "work_minutes"
	InterruptCount   = "interrupt_count"
	ExtiCount        = "exti_count"
	ExtiDuration     = "exti_duration"
	MoveCount        = "move_count"
	SystemTimestamp  = "system_timestamp"
	AccelerationX    = "acceleration_x"
	AccelerationY    = "acceleration_y"
	AccelerationZ    = "acceleration_z"
	MaxAccelerationX = "max_acceleration_x"
	MaxAccelerationY = "max_acceleration_y"
	MaxAccelerationZ = "max_acceleration_z"
	DoorOpenStatus   = "door_open_status"
	WaterLeakStatus  = "water_leak_status"
	Alarm            = "alarm"
)

// Additional canonical names for multi-channel and vendor-family readings.
const (
	Major                  = "major"
	Minor                  = "minor"
	RSSI                   = "rssi"
	Power                  = "power"
	StepCount              = "step_count"
	Distance1CM            = "distance_1_cm"
	Distance2CM            = "distance_2_cm"
	Distance3CM            = "distance_3_cm"
	Distance4CM            = "distance_4_cm"
	DistanceSignalStrength = "distance_signal_strength"
	LidarTemperature       = "lidar_temperature"
	InterruptStatus        = "interrupt_status"
	InterruptFlag          = "interrupt_flag"
	MessageType            = "message_type"
	TemperatureProbe       = "temperature_probe"
	TemperatureProbeMin    = "temperature_probe_min"
	TemperatureProbeMax    = "temperature_probe_max"
	Temperature2           = "temperature_2"
	Temperature3           = "temperature_3"
	SHTTemperatureMin      = "sht_temperature_min"
	SHTTemperatureMax      = "sht_temperature_max"
	SHTHumidityMin         = "sht_humidity_min"
	SHTHumidityMax         = "sht_humidity_max"
	TempRed                = "temperature_red"
	TempWhite              = "temperature_white"
	TempBlack              = "temperature_black"
	TempRedMin             = "temperature_red_min"
	TempRedMax             = "temperature_red_max"
	TempWhiteMin           = "temperature_white_min"
	TempWhiteMax           = "temperature_white_max"
	TempBlackMin           = "temperature_black_min"
	TempBlackMax           = "temperature_black_max"
	TempChannel1           = "temperature_1"
	TempChannel2           = "temperature_2"
	Resistance1            = "resistance_1"
	Resistance2            = "resistance_2"
	ADCCH0Voltage          = "adc_ch0_voltage"
	ADCCH1Voltage          = "adc_ch1_voltage"
	ADCCH4Voltage          = "adc_ch4_voltage"
	AnalogVoltage1         = "analog_voltage_1"
	AnalogVoltage2         = "analog_voltage_2"
	CurrentMA1             = "current_ma_1"
	CurrentMA2             = "current_ma_2"
	EventCount             = "count"
	Count1                 = "count_1"
	Count2                 = "count_2"
	CountA                 = "count_a"
)

// Canonical units.
const (
	Volt             = "V"
	Celsius          = "C"
	Percent          = "%"
	Millimeter       = "mm"
	Centimeter       = "cm"
	PPM              = "ppm"
	PPB              = "ppb"
	MilliAmp         = "mA"
	Lux              = "lx"
	Count            = "count"
	Degree           = "deg"
	Meter            = "m"
	Second           = "s"
	Minute           = "min"
	Gram             = "g"
	GForce           = "g"
	MicroSiemens     = "uS/cm"
	Ohm              = "ohm"
	DecibelMilliwatt = "dBm"
	MilligramPerKG   = "mg/kg"
)
